server:
  port: 8000

spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flash_cards
    username: lazarev
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
        hbm2ddl:
          auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false

  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB

jwt:
  config:
    secret: 'YXNkZ2pwdWh2Ym56cG9pbndiZ3BpcnVnYm5lYW9zZGc='
    tokenExpirationMs: 36000000
#    tokenExpirationMs: 30000

flash-card:
  primary-correct-answers: 3
  spaced-repetition-pattern: 2x+1
  days-factor: 2
  days-additional: 1